---
title: "Testing K-Prototypes"
author: "Juan Bernal"
date: "21/06/2021"
output: html_document
---
<h1>Testing K-Protoypes</h1>

<h3>Libraries</h3>

```{r}
library(tidyverse)
library(clustMixType) #Contains kproto() function for k-prototype clustering.
library(factoextra)
library(clValid)

```

<h3>Import previously processed data</h3>
```{r}
#This loads the file I had saved in the NY Airbnb EDA Draft 2.rmd file with the save() function
load(file="airbnb_df.Rdata")
```



<h3>Convert the char variables to factors</h3>
```{r}
airbnb_df$neighbourhood_group<-factor(airbnb_df$neighbourhood_group)
airbnb_df$neighbourhood<-factor(airbnb_df$neighbourhood)
airbnb_df$room_type<-factor(airbnb_df$room_type)

```

<h3>Scale the data</h3>
```{r}
#Scaling the data first

#Note:Neighbourhood is dropped
airbnb_df_scaled<-airbnb_df[,-2]
airbnb_df_scaled[,-c(1,4)]<-scale(airbnb_df_scaled[,-c(1,4)])


```

<h3>Determine K</h3>

A custom function
```{r}
#Determine K 
#This will use the elbow method to determine which k value reduces the within variability of the clusters the most. Seems like it's 7 or 8

#This function will run kproto() k times and return the total WSS of the clusters.
wss <- function(k) {
  clustMixType::kproto(x=airbnb_df_scaled, k)$tot.withinss #The kproto object has the total Within Sum of Squares of the clusters. We want a K value that reduces this.
}
kvalues <- 1:15

wss_values <- map_dbl(kvalues, wss) #Applies the wss function to each element in k.values

plot(kvalues, wss_values,
       type="b", pch = 19, frame = FALSE,
       main="Reduction in WSS per K value",
       xlab="Number of clusters K",
       ylab="Total within-clusters sum of squares")
```


<h3>Run the algorithm:kproto()</h3>

```{r}
#Using the k value determined above k=8
set.seed(1234)
airbnb_proto<-kproto(x=airbnb_df_scaled,k=8,iter.max=50)
#A methodologically based iter.max value has not yet been chosen.Will require more research but in the meanwhile I just use 50.
```

<h3>Add the clusters to original data as labels and make some plots</h3>
```{r}
airbnb_df_clustered<-airbnb_df %>%
  mutate("cluster"=airbnb_proto$cluster,.before=neighbourhood_group)
```

```{r}
#Plot the clusters in a bar graph faceted by different variables of interest.
neighbourhoodGroupByCluster<-ggplot(data=airbnb_df_clustered,aes(x=neighbourhood_group))+
         geom_bar()+
         labs(title="Neighbourhood Groups distribution in each cluster",x="neighbourhood_group",y="Number of listings")+
         coord_flip()+
         facet_wrap(~cluster,nrow=3)

neighbourhoodGroupByCluster
```


```{r}
priceByCluster<-ggplot(data=airbnb_df_clustered,aes(x=price))+
         geom_histogram()+
         labs(title="Price distribution in each cluster",x="price",y="Number of listings")+
         facet_wrap(~cluster,nrow=3)

priceByCluster
```

```{r}
room_typeByCluster<-ggplot(data=airbnb_df_clustered,aes(x=room_type))+
         geom_bar()+
         labs(title="Room type distribution in each cluster",x="room_type",y="Number of listings")+
         facet_wrap(~cluster,nrow=3)
room_typeByCluster
```
<h3>Plot clusters in a map</h3>
```{r}
#WIP - Still have not been able to get this section working
aribnb_proto_visualize<-clustMixType::clprofiles(object=airbnb_proto,x=airbnb_df)
```

```{r}
#WIP - Still have not been able to get this section working
factoextra::fviz_cluster(airbnb_proto,data=airbnb_df_scaled)
```

<h3>Evaluating the clusters with Dunn metric</h3>

```{r}
#On my machine the dunn() and connectivity() algorithms could not run without allocating more memory with the memory.limit() function.
memory.size() ### Checking your memory size
memory.limit(size=56000) ## Checking the set limit 
```

```{r}
#Commenting this function out as it takes a very long time to run so I only did it once.
clValid::dunn(Data=airbnb_df_clustered,clusters=airbnb_proto$cluster) #0.001901993
```
<h3>Evaluating the clusters with Connectivity metric</h3>

```{r}
#Commenting this function out as it takes a very long time to run so I only did it once.
#clValid::connectivity(Data=airbnb_df_clustered,clusters=airbnb_proto$cluster) #28376.36
```
